### ISSUE TITLE
Possible to get moon phase in precentage?

### ISSUE THREAD

**Issue by deepcoder** [ngocjohn/lunar-phase#1]
Thank you for your work on this!

Would it be possible to get a numeric percentage value for the moon's phase?

**Comment by ngocjohn** [comment]
The integration provides an illumination fraction sensor that shows the percentage of the moon’s surface that is illuminated. While it doesn’t directly give a percentage for the moon’s phase, the illumination fraction closely matches the phase.. 

So, for example:
If the illumination fraction sensor shows that the moon’s surface is 95.3% illuminated, it indicates that the moon is in the Waxing Gibbous phase, close to being a Full Moon. The illumination fraction gives you a numeric percentage that helps you understand the moon’s phase more precisely.

•	0% illumination corresponds to a New Moon.
•	50% illumination corresponds to the First Quarter or Last Quarter.
•	100% illumination corresponds to a Full Moon.
