### ISSUE TITLE
[Bug] Wrong status "waning crescent" where it should be "waxing" now

### ISSUE THREAD

**Issue by NoRi2909** [ngocjohn/lunar-phase#14]
### Short summary 📝

Switches to wrong "waning crescent" after new moon

### Detailed description 📋

The moon just started to grow again after the new moon this weekend.

But lunar-phase switched back to "waning crescent" now, while it should be "waxing crescent" instead.

### Version 📌

0.2.1

### Environment 🌐

Chrome OS 131

### Logs and screenshots 📂

![image](https://github.com/user-attachments/assets/42a53fb7-af06-4c08-bc45-2516985a9d72)

**Comment by ngocjohn** [comment]
Hi @NoRi2909 , the bug is fixed in the [last release](https://github.com/ngocjohn/lunar-phase/releases/tag/v0.2.2). Thanks for reporting. 👍
