### ISSUE TITLE
[Bug] Setup failed for custom integration 'lunar_phase': Requirements for lunar_phase not found: ['ephem==4.1.5'].

### ISSUE THREAD

**Issue by nemoBE** [ngocjohn/lunar-phase#16]
### Short summary 📝

Setup failed for custom integration 'lunar_phase': Requirements for lunar_phase not found: ['ephem==4.1.5'].

### Detailed description 📋

After updating to HA 2024.12.0 the integration does not load anymore with the above error message.

### Version 📌

0.2.0

**Comment by ngocjohn** [comment]
Hi @nemoBE, update the integration to latest release v0.2.2

**Comment by nemoBE** [comment]
Thanks, that worked
