### ISSUE TITLE
[Feature] Sensors for Dates of last Key Moon Phases

### ISSUE THREAD

**Issue by nicknol** [ngocjohn/lunar-phase#6]
### Short summary

Add Sensors for dates of last Key Moon Phases

### Detailed description

The integration already provides sensors for the dates of the _next_ key phases. It would be convenient to have dates for the _last_ key phases as well.

My use case
Most nights we like to see the sky and the stars while going to bed and sleep, but during the days before, on, and after full moon the moon illuminates our bed room too much, it's hard to get to sleep. Hence we close the blinds manually each evening and open them in the morning via the homeassistant companion app.
It would be very convenient to close the blinds automatically each evening (e.g. at sunset) during the days of full moon, means starting 3 days before and finishing 3 days later. 
The first one is already possible with this integration, my feature request is about the second one: how many days have past since the last full moon. 

Yes, I could calculate that myself and create a template sensor that I add to the lunar-phase device :)
having it our of the box would just me more convenient and could help others.

**Comment by nicknol** [comment]
I think I could achieve my goal using the illuminance sensor, nevertheless having the dates at hand would still be convenient.

**Comment by ngocjohn** [comment]
I think you can do a simple automation using the next full moon sensor and combination with the illuminance sensor. Sensor next moon phase, shows only the next closest phase.

**Comment by nicknol** [comment]
using the illuminance sensor is a far better option - thanks for the pointer.
